name: Build Tests
on: [push]
jobs:
  build-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: swipes-server
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Attempt to start server
        run: yarn build --if-present
        env:
          CI: true
  build-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: swipes-site
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Attempt to run
        run: yarn build --if-present
        env:
          CI: true
            



